sonar.projectKey=Bhavan-Booking-frontend
sonar.projectName=Bhavan-Booking-frontend
sonar.projectVersion=1.0

sonar.sources=src

sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonarqube.qolarisdata.com
sonar.token=sqp_7ecfdd897cbb1022b0d60834fdb76d9706e8b550

sonar.exclusions=**/node_modules/**,**/build/**
sonar.coverage.exclusions=src/**/*
sonar.javascript.lcov.reportPaths=coverage/lcov.info